# To revert option to default settings (for scripting etc):
# emulate -LR zsh


source ~/config/zsh/ohmyzsh
source ~/config/zsh/my-custom-code
# source ~/config/zsh/conda

source ~/powerlevel10k/powerlevel10k.zsh-theme

plugins=(git zsh-autosuggestions zsh-syntax-highlighting)
source ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

setopt CORRECT
setopt CORRECT_ALL

export PATH="/usr/local/sbin:$PATH"
